# Generated by Django 5.1.5 on 2025-01-17 09:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('type_of_meal', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('height', models.BigIntegerField()),
                ('weight', models.BigIntegerField()),
                ('daily_insulin_level', models.FloatField(blank=True, null=True)),
                ('dietary_preferences', models.TextField(blank=True, default='', null=True)),
                ('family_history', models.TextField(blank=True, default=False, null=True)),
                ('physical_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('alcohol_use', models.BooleanField(default=False)),
                ('household_income', models.BigIntegerField(blank=True, null=True)),
                ('health_report', models.ImageField(blank=True, null=True, upload_to='health_reports/')),
            ],
        ),
        migrations.CreateModel(
            name='Meal_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('recipes', models.ManyToManyField(to='nutrition.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.userprofile')),
            ],
        ),
    ]
