# Generated by Django 5.1.5 on 2025-01-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipes_images',
            field=models.ImageField(blank=True, null=True, upload_to='recipes_images/'),
        ),
    ]
