# Generated by Django 5.1.4 on 2025-01-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_recipe_recipes_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='diet',
            field=models.CharField(blank=True, choices=[('diabetic friendly', 'Diabetic Friendly'), ('vegetarian', 'Vegetarian'), ('non vegetarian', 'Non Vegetarian'), ('vegan', 'Vegan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family_history',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(),
        ),
    ]
