# Generated by Django 5.1.4 on 2025-01-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_recipe_diet_alter_userprofile_family_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='family_history',
            field=models.CharField(blank=True, choices=[('diabetic', 'Diabetic'), ('non_diabetic', 'Non Diabetic')], max_length=20, null=True),
        ),
    ]
