# Generated by Django 5.1.4 on 2025-01-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_alter_userprofile_family_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='health_condition_preferences',
            field=models.CharField(blank=True, choices=[('diabetes', 'Diabetes'), ('cardiovacular', 'Cardivascular')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('non vegetarian', 'Non Vegetarian'), ('vegan', 'Vegan')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='physical_activity',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary (Minimal movement, mostly sitting)'), ('low_active', 'Low active (Light physical activity, occasional exercise)'), ('active', 'Active (Regular exercise, moderate physical activity)'), ('very_active', 'Very active (Intense daily physical activity or workouts)')], max_length=20, null=True),
        ),
    ]
