# Generated by Django 5.1.4 on 2025-01-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_userprofile_health_condition_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='household_income',
        ),
    ]
